name: Go Git Operations

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Build code
      run: make   

    - name: Run md2html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        APP_SOURCE_FOLDER: thoughts
        APP_HTML_TEMPLATES: "template/index.gohtml,template/navbar.gohtml,template/content.gohtml"
      run: |
        ./bin/md2html